### ISSUE TITLE
Duplicate nodes in xod/core — "clip" and "constrain"

### ISSUE THREAD

**Issue by evgenykochetkov** [xodio/xod#1081]
Implementations are identical:
https://github.com/xodio/xod/blob/8ccbf4334cc5773b56ff5d586ca329fd850354a5/workspace/__lib__/xod/core/constrain/patch.cpp#L10-L13

https://github.com/xodio/xod/blob/8ccbf4334cc5773b56ff5d586ca329fd850354a5/workspace/__lib__/xod/core/clip/patch.cpp#L10-L17

**Comment by nkrkv** [comment]
Solved in #1251. Now, there’s only `xod/math/clip`.
