### ISSUE TITLE
Grove DHT22 (AM2302) and I2C LCD do not work together

### ISSUE THREAD

**Issue by nkrkv** [xodio/xod#1110]
The problem [reported on the forum](https://forum.xod.io/t/problem-with-dht22-am2302-grove/536/2)

### Steps to reproduce

1. Build a circuit with [Grove DHT22](https://www.seeedstudio.com/Grove-Temperature&Humidity-Sensor-Pro-p-838.html) on port D2 and a text I2C display
2. Make a program to show temperature and humidity from the sensor on the screen
3. Upload

### Expected behavior

LCD shows actual values

### Actual behavior

LCD shows zeros for both T and RH

### Details

It was verified another very similar AM2301 sensor works fine with an I²C display, but it looks like AM2302 differs somehow.

Help from one who has following is required:

- Grove DHT22
- I²C Text LCD
- C++ knowledge and Arduino debug skills

The following yet to be done:

- Confirm or decline the bug
- Find the root cause

**Comment by maroelawerner** [comment]
I have the same problem. Tested DHT22 sensor using the Arduino IDE and the DHTlib and it works well. Using XOD it just shows values of 0.00.

**Comment by evgenykochetkov** [comment]
@maroelawerner, did you use XOD v0.25.0?

**Comment by maroelawerner** [comment]
I have upgraded to V0.25.0 and tried out you recommendation. 
Still the same.
BTW. The original project had a square wave generator connected to the UPD.

**Comment by evgenykochetkov** [comment]
Then please also update to v0.25.0. Among [other nice stuff](https://github.com/xodio/xod/releases/tag/v0.25.0), it comes with fixes for DHT11 and DHT2x nodes.

**Comment by maroelawerner** [comment]
Hi, 

I'm using an Arduino clone and an AM2302. 

I have attached some pictures showing you the details of the setup. 
I have also have pictures of the oscilloscope traces. With the XOD download, there is just a high level after a short low. With the Arduino IDE download, that works without changing the hardware at all, you can see the exchange of data taking place. It looks like the request to send data is not handled properly by the XOD code.

[temp-humid.xodball.zip](https://github.com/xodio/xod/files/2498084/temp-humid.xodball.zip)
![osc5](https://user-images.githubusercontent.com/2838509/47256143-f5cccc80-d472-11e8-8830-7e470ba9feda.png)
![osc4](https://user-images.githubusercontent.com/2838509/47256146-fb2a1700-d472-11e8-9934-b1a0284d9bb6.png)
![screenshot_20181020_140247](https://user-images.githubusercontent.com/2838509/47256161-2ca2e280-d473-11e8-8266-e5699a13ba82.png)
![20181020_124713](https://user-images.githubusercontent.com/2838509/47256198-b783dd00-d473-11e8-8a8d-06284ab9f104.jpg)
![20181020_124641](https://user-images.githubusercontent.com/2838509/47256213-f6b22e00-d473-11e8-95a2-5d68f229a9ba.jpg)

**Comment by maroelawerner** [comment]
missed one picture
![osc3](https://user-images.githubusercontent.com/2838509/47256288-6ffe5080-d475-11e8-9b15-91659d1acfdf.png)

**Comment by evgenykochetkov** [comment]
@maroelawerner, thanks for the detailed report!

That still looks a lot like `xod/common-hardware/dht2x-thermometer` from v0.24.x🤔
Don't  you by any chance have an old version of `xod/common-hardware` in your `~/xod/__lib__`?

**Comment by nkrkv** [comment]
Should be fixed by #1853
