### ISSUE TITLE
Legalize parametric patch names

### ISSUE THREAD

**Issue by nkrkv** [xodio/xod#1114]
### Rationale

To support generics we should allow patch names which define the type(s) they specialize for:

- `if-else(number)`
- `if-else(string)`
- `cast(boolean,pulse)`

### Acceptance criteria

The following are legal and can be created via IDE:

- [ ] `if-else(number)`
- [ ] `cast(boolean,pulse)`

The following is not:

- [ ] `if-else(number`
- [ ] `if-else ( number )`
- [ ] `if-else)`
- [ ] `if-else()`
- [ ] `if-else(number)string`

### Out of scope

- Any special meaning for the patches with parenthesis in their name.
- Fancy rendering of parametric patch names

**Comment by brusherru** [comment]
Spaces will be ugly in the URLs for library docs.
So maybe keep patch paths without spaces, but for better readability, we could render it with spaces in the GUI?

**Comment by nkrkv** [comment]
URLs :thinking: Very good point!

OK, I agree. Will try to use GUI-only spaces or better half-spaces or quarter-spaces. Whatever will work better visually. I’ll edit the issue body.
