### ISSUE TITLE
Mark links between incompatible types with errors

### ISSUE THREAD

**Issue by nkrkv** [xodio/xod#1118]
### Rationale

To better support generic type resolution edge-cases and handle possible xodball inconsistencies we should accept links between pins of incompatible types and mark them with an error. That does *not* mean we should allow creating such links directly, the current behavior must be preserved, but if a bad link already appeared in the project somehow, that’s should not be a show-stopper.

### Acceptance criteria

Create a `boot` node and a `not` node. Edit xodball manually to make a link between the nodes. Then open the project.

- [x] The link is drawn in red
- [x] On hover a tooltip is shown with a message like: “Type pulse can’t cast to boolean directly”
- [x] On attempt to transpile an error message is shown¹

¹
```markdown
**Program contains bad links** 
@/main -> @/foo -> @/bar: type pulse can’t cast to boolean directly.
Delete the bad link or place an explicit conversion node in-between to continue.
```

Please, attach the test xodball to the PR or issue.

**Comment by brusherru** [comment]
Xodball:
[broken-link.xodball.zip](https://github.com/xodio/xod/files/1811826/broken-link.xodball.zip)
