### ISSUE TITLE
Can’t unbind values from generics

### ISSUE THREAD

**Issue by nkrkv** [xodio/xod#1221]
### Environment

- Scope: desktop IDE, browser IDE, CLI
- Version: master, 079ab358e6d25eef913bd4f00ae2df7613c36ec6

### Steps to reproduce

1. Place an `if-else` node
2. Bind `42` to `T`
3. Clear the value for `T` and press Enter

### Expected behavior

The node switches to the initial state, that is nothing bound

### Actual behavior

`T` pin goes red with an error “Value undefined bound to T is invalid”

**Comment by brusherru** [comment]
Also, we have a problem with binding some bytes and "almost valid" types.
Try to bind `32d` or `true` in the generic pin.

**Comment by nkrkv** [comment]
Are you sure they’re related? If not, that should be a separate issue.
