### ISSUE TITLE
As a xoder I want to make HTTP requests via ESP8266 so that I can publish and consume API data

### ISSUE THREAD

**Issue by nkrkv** [xodio/xod#1288]
### Rationale

HTTP requests open endless possibilities to integrate a device into the world. ESP8266 is technically capable to do it (although without TLS), let’s make a node to make it possible with XOD.

### User story

A xoder places an `esp8266-device` and `wifi-connect` onto a patch. Then he can feed the device to a `http-request(esp8266-device)` node. The node also takes a request object of type `xod/net/http-request`. For that request two constructors exist:

- `xod/net/http-get-request`
- `xod/net/http-post-request`

Both take `URL` and `HDRS`, whereas “post” additionally takes `BODY`. All of them are strings.

The `http-request` node outputs `RESP` which is a `xod/net/http-response`. The `xod/net/unpack-http-response` might be used to extract `CODE`, `HDRS`, and `BODY`.

The `http-request` also takes care about adding vital headers:

- `Host`
- `Content-Length` (in case of POST)
- `Connection: close`

### Prerequisites

#1286 

### Acceptance criteria

- [ ] I can HTTP POST to a local web-server and see the request is well-formed
- [ ] I see the `CODE`, `HDRS`, and `BODY` received on a board presented as they were replied by the local web-server
- [ ] I can HTTP GET in the same way as HTTP POST

**Comment by brusherru** [comment]
It was implemented within PR #1322, forgot to point on this issue in PR. 😬
