### ISSUE TITLE
Transpilation fails trying to find a patch with empty path

### ISSUE THREAD

**Issue by nkrkv** [xodio/xod#1304]
Reported on forum https://forum.xod.io/t/transpiling-error-message/892

### Environment

- Scope: desktop IDE
- Version: 0.21.1

### Steps to reproduce

1. Open the [xodball](https://github.com/xodio/xod/files/2137177/RW_SD_card.zip)
2. Hit Deploy → Show Code for Arduino

### Expected behavior

Either the code or a clear message is shown

### Actual behavior

Snackbar error is shown:

```
Error
Can't find the patch in the project with specified path: """
The error was not caught, which is a bug. Report the issue to XOD developers.
```

**Comment by evgenykochetkov** [comment]
Apparently, XOD does not handle well the situation when user expands a variadic node, binds values to the rightmost pins, and then collapses it back.
