### ISSUE TITLE
Error, `clip` node output pin label lost.

### ISSUE THREAD

**Issue by gabbapeople** [xodio/xod#1305]
**Issue**
`clip` node hasn't got output pin label.

![121212121212](https://user-images.githubusercontent.com/35202630/41916159-164b239e-7960-11e8-9b6b-776a47dfa50c.png)

**Upload log error**

error: 'output_**Xc**' was not declared in this scope
     emitValue<output_Xc>(ctx, xc);

**Comment by nkrkv** [comment]
Confirm. Should be `emitValue<output_OUT>(ctx, xc)`
