### ISSUE TITLE
Create tabtests for every xod/math node

### ISSUE THREAD

**Issue by nkrkv** [xodio/xod#1321]
### Rationale

There can be surprises from XOD standard library. Thus it should be tested hard. `xod/math` is purely functional, so it should be not so hard to cover it with tests completely. Other libraries’ coverage is required by other issues.

### Acceptance criteria

- [x] Every patch in `xod/math` has a tabtest

**Comment by brusherru** [comment]
Closed by https://github.com/xodio/xod/pull/1531
