### ISSUE TITLE
Make watches and constants resizable

### ISSUE THREAD

**Issue by nkrkv** [xodio/xod#1354]
### Rationale

It’s often desired that watches and constants may have a quite long label which can’t fit one slot. Sometimes it makes them just unusable. Let xoders resize the watches and constants with the same UX as they have when resizing comments.

### Acceptance criteria

- [ ] I can drag the bottom right corner of any `watch` or `xod/core/constant-*` to adjust the node’s width and height (in steps of a slot)
- [ ] The label aligns to center/middle regardless of size

### How to implement

- Make the ability to resize a `Node` attribute. Having that we can later easily transform the comments as a separate issue to nodes with a special borderless look.
- Store the desired size in `Node` as `size: { x: 42, y: 22 }`
- Use the size of one slot as default
- Throw away defaults on saving
- Right after manual resize compare the new size with one that deduced automatically and if they match, set `size` to default.

**Comment by evgenykochetkov** [comment]
Resizing a watch node while in debug mode will stop debug mode(because the patch has changed).
I think we'll need to address that as well.

**Comment by nkrkv** [comment]
Addressed in #1368
