### ISSUE TITLE
Tab contents are not centered vertically

### ISSUE THREAD

**Issue by nkrkv** [xodio/xod#1416]
Observable in 0.23.0, but seems the flaw is out there for months already

Look at the tab titles and close buttons in tabs:

![screenshot from 2018-08-20 12-56-38](https://user-images.githubusercontent.com/146383/44334009-154a7780-a479-11e8-9eaa-7d4de5197fdc.png)

Their baseline is aligned to the tabline bottom, however in most UI’s the content should be vertically-centered to the tabline height. Let’s fix it to be a bit more intuitive.

**Comment by brusherru** [comment]
Fixed by referenced PRs.
