### ISSUE TITLE
Common four-character labels are clipped in buses and terminals

### ISSUE THREAD

**Issue by nkrkv** [xodio/xod#1417]
### Environment

- Version: 0.23.0 (in 0.22.0 was OK)

### Steps to reproduce

1. Place an `input-pulse` terminal
2. Place a `to-bus` node
3. Give both a label “DONE”

### Expected behavior

The labels are rendered completely

### Actual behavior

The labels are rendered as “DON…”

### How to fix

The reason is probably in the node padding added for the feature of node resize. Although it works fine for regular nodes, when applied to terminals and busses it hurts more than helps: the very common four-character abbrevs get truncated to two or three chars.

Let’s make the margin zero for terminals and buses.

**Comment by brusherru** [comment]
Fixed by referenced PRs.
