### ISSUE TITLE
Ampersand is not shown for Upgrade Packages menu item

### ISSUE THREAD

**Issue by nkrkv** [xodio/xod#1480]
### Environment

- Scope: desktop IDE
- Version: 0.25.0
- OS: Arch Linux, Gnome 3

### The bug

The Deploy menu item:

```text
actual: Upgrade Arduino Packages  Toolchains
expect: Upgrade Arduino Packages & Toolchains
```

### How to fix

- Endouble the `&` (https://github.com/electron/electron/issues/9584)
- Check on macOS, Windows, Linux

**Comment by evgenykochetkov** [comment]
Closed by #1483
