### ISSUE TITLE
Preserve compiler output completely

### ISSUE THREAD

**Issue by nkrkv** [xodio/xod#1499]
The compilation log is truncated now and may possibly hide vital compilation error details.

### Steps to reproduce

1. Remove all temporary compilation files to ensure no objects are pre-compiled
2. Upload to a board
3. Switch to the Compiler tab and scroll to the top

### Expected behavior

I see the output from the very beginning

### Actual behavior

Incomplete log with `=== Older lines are truncated ===`

**Comment by brusherru** [comment]
Fixed with PR #1502, but not closed because it merged into `0.25.x`
