### ISSUE TITLE
Stale arduino-cli process after closing the IDE

### ISSUE THREAD

**Issue by brusherru** [xodio/xod#1501]
### Environment
- Scope: desktop IDE
- Version: 0.25.x
- Any OS

### Steps to reproduce
1. Open IDE
2. Deploy -> Upload to Arduino
3. Select any board that is not installed yet
4. Click "Upload" and then begin installing
5. Close the IDE before installation is done

### Expected behavior
IDE closed, the process in the terminal (dev version) is killed and there is no running `arduino-cli` process on the machine.

### Actual behavior
On Linux/MacOS main process stale for some time and when it terminated it terminates `arduino-cli` process too. ( https://github.com/xodio/xod/pull/1500#issuecomment-432636190 )
On Windows `arduino-cli` process still running until it completely installs package (or failed).

**Comment by nkrkv** [comment]
I’m almost sure it is up to Electron’s main to kill the child processes on exit. See https://stackoverflow.com/questions/36031465/electron-kill-child-process-exec
