### ISSUE TITLE
Snackbar messages show on top of popups

### ISSUE THREAD

**Issue by evgenykochetkov** [xodio/xod#1504]
![screen shot 2018-10-10 at 18 46 06](https://user-images.githubusercontent.com/2527093/47450039-ddd7ae80-d7cc-11e8-992f-67acf9af965f.png)

**Comment by brusherru** [comment]
Just checked it on `0.25.x` branch. Is it still actual or it was already fixed?

**Comment by brusherru** [comment]
Fixed here: https://github.com/xodio/xod/commit/0416e0a22c6ea9362215df5965222c4c6edc4869#diff-5e15a00741f7c672a61dc48b2b30be5f
