### ISSUE TITLE
Make download&install messages persistent

### ISSUE THREAD

**Issue by brusherru** [xodio/xod#1550]
To allow a user to notice and respond to a message that requires action, let's make such messages persistent:
- Update available
- Install packages and toolchains
- Install arduino libraries

**Comment by knopki** [comment]
ARDUINO_DEPENDENCIES_MISSING (Arduino dependencies missing) is fixed in #1548

**Comment by nkrkv** [comment]
Duplicate of #1613 which is closed already by #1614
