### ISSUE TITLE
Select all, works just by pressing "A"

### ISSUE THREAD

**Issue by Cesar-S** [xodio/xod#1552]
### Expected behavior

To select all the content of the patch, Ctrl + A must be used.

### Actual behavior

- Using  the A key, select all the content.

- Using  Ctrl + A, select all the content.

Conclusion, Ctrl is not necessary, to use the shortcut.

**Comment by nkrkv** [comment]
Although it is an interesting suggestion it is a controversial feature which should be discussed on the [forum](https://forum.xod.io) first. I cannot accept it to the backlog as is at its current state, so I’m closing the issue for now. It might be re-opened in the future if the community accepts the idea.

**Comment by nkrkv** [comment]
:astonished: My bad, sorry. I thought the proposal was to change from Ctrl+A to A (which is interesting albeit controversial).

Definitely a bug.

**Comment by Cesar-S** [comment]
Solved. Thanks
