### ISSUE TITLE
Forbid `getValue` for pulses

### ISSUE THREAD

**Issue by nkrkv** [xodio/xod#1572]
As [reported on the forum](https://forum.xod.io/t/possible-bug-with-generic-input-patch-node-pulse-inputs/1415) checking for a pulse presence is somewhat confusing.

Indeed, pulses are very special in the sense they are the only reactive type, other types are continuous. So, doing `getValue<input_MYPULSE>` makes a little sense and should lead to a compile-time error. The error should say that using `isInputDirty<input_MYPULSE>` is the proper way to check for the pulse.

**Comment by evgenykochetkov** [comment]
#1925 makes `getValue` behave same as `isInputDirty` for pulses.
