### ISSUE TITLE
Do NOT save terminals for users custom types

### ISSUE THREAD

**Issue by brusherru** [xodio/xod#1593]
### Environment
* Scope: desktop IDE
* Version: 0.25.3

### Steps to reproduce
1.  Create new project
2.  Create patch `a` and place `output-self` and `not-implemented-in-xod`
3.  Save project as a multi-file project

### Expected behavior
On FS in the project directory, we will see two directories: `main`, `a` and `project.xod` file.

### Actual behavior
It also saves `input-a` and `output-a`.

**Interesting thing**
If you delete it manually and then reload project and save again — it will not be saved again. So it reproduces only on the first saving of the project.

**Comment by nkrkv** [comment]
Closed by #1603
