### ISSUE TITLE
Pop-Up switch workspace bug

### ISSUE THREAD

**Issue by Cesar-S** [xodio/xod#1596]
## If I do not select a directory I can not close popup

When he makes this video I find the problem. [foro](https://forum.xod.io/t/dual-workspace-in-xod/1585)

### Environment

* Scope: desktop IDE
* Version: 0.25.3
* OS: Windows 10

### Steps to reproduce

https://www.youtube.com/watch?v=ucbZRDnvt-w

### Expected behavior

If I select by mistake, or regret having changed, I can close the pop-up

### Actual behavior

It does not allow me to close popup without first selecting a workspace

**Comment by nkrkv** [comment]
Thank you. I’ve put the issue onto the backlog.
