### ISSUE TITLE
Saving files after opening IDE using associated files

### ISSUE THREAD

**Issue by brusherru** [xodio/xod#1612]
### Environment

* Scope: desktop IDE
* Version: 0.26.0
* OS: Any

### Steps to reproduce
1. Open any associated file (xodball / xod)
2. Click File -> Save (Ctrl+S)

### Expected behavior
The project saved without any questions.

### Actual behavior
IDE asks where to save the project.

---
Bug reproduces only when IDE opens with opening associated file.
Probably it introduced here: https://github.com/xodio/xod/pull/1587

**Comment by Cesar-S** [comment]
It happens when you open a project.xod or an .xodball directly. Opening from IDE no problem.

**Comment by nkrkv** [comment]
Closed by #1615
