### ISSUE TITLE
Add pulse tweaks

### ISSUE THREAD

**Issue by nkrkv** [xodio/xod#1627]
Sending pulses in an interactive session is useful, however, they are not so simple. There’s no natural way to send a pulse via Inspector while we are in development mode. So, an extra mechanism is required.

### User story

- I put a `tweak-pulse` node and connect it to a `led` through `flip-flop`
- I upload with the debugger and the debug session starts
- Now if I select the `tweak-pulse` its input box with disabled “pulse” placeholder gets replaced with a button “pulse” in the Inspector
- Clicking the button I toggle my LED on and off

### Acceptance criteria

* [ ] The basic scenario works as described
* [ ] The node is available under `xod/debug`
* [ ] Node’s color behaves as for other tweaks
* [ ] The button replaces text input only while the debug session is active and its tab is selected

**Comment by evgenykochetkov** [comment]
After #1681 implementing this is much easier
