### ISSUE TITLE
enhancement: add feature to bend links

### ISSUE THREAD

**Issue by donovaly** [xodio/xod#1637]
### Environment

* Scope: all
* Version: 0.26.1
* OS: all
* Machine: all

### Problem

When you have many links you loos the overview quiclkly. Therefore XOD offers buses. However, sometimes XOD should look cleaner also in a patch has only few nodes. Take for example this:

![link-not-bended](https://user-images.githubusercontent.com/1828501/51483440-57197a00-1d99-11e9-8bd6-60f13a769322.jpg)

There it would look cleaner if the links to the watches would have a curve.

### Solution

Add a feature to bend links. in most cases it would be sufficient if links could have one curve. Take as reference the curve line connector in LibreOffice draw:

![curve-line-connector-lo-draw](https://user-images.githubusercontent.com/1828501/51483365-2fc2ad00-1d99-11e9-97d4-6ec0bf80bfee.jpg)

**Comment by nkrkv** [comment]
This was discussed before and we refuse to accept the feature in this way

> That’s a very questionable thing that did not get a consensus yet. The problem is not in bending and curves per se but is in the fact everyone wants to see a clear graph without intersections, overlaps, etc. If we’d give arbitrary control of link shape I afraid that would be perfectionist hell. Instead of making a program, he would spend most of the time in search for a nonexistent layout perfecto. I’m struggling to find a way when all links would bend automatically to achieve the best readability result.

There’s a `xod/patch-nodes/jumper` which can be used as a dummy to change the visual link path if absolutely required. We should change its face to be rendered specially, as a straight line, without the rectangle and label.

**Comment by nkrkv** [comment]
As we have #1645, I’m closing this issue for now.

Also, consider using [buses](https://xod.io/docs/guide/buses/) when you get too many links.
