### ISSUE TITLE
enhancement: add shortcuts for common tasks

### ISSUE THREAD

**Issue by donovaly** [xodio/xod#1642]
### Environment

* Scope: desktop IDE
* Version: 0.26.1

### Problem

there are no shortcuts yet for these often used menu entries:
* Edit -> Insert Node...
* Edit -> Insert Comment
* Deploy -> Upload to Arduino

### Solution

* At least predefine shortcuts for these 3 entries
* If possible add a menu entry where one can set and change shortcuts

This issue might seem minor but usability is important on real life and shortcuts are important to speed up working with a program.

**Comment by nkrkv** [comment]
Thanks for the feedback

> Edit -> Insert Node...

There’s `I` shortcut, but it is not shown. See #1646 

> Edit -> Insert Comment

This is not relevant because of #1380 

> Deploy -> Upload to Arduino

In #862 already
