### ISSUE TITLE
Utility marker ignored on lib install

### ISSUE THREAD

**Issue by Cesar-S** [xodio/xod#1697]
### Environment

* Scope: desktop IDE
* Version: 0.27.0
* OS: Windows 10 

### Steps to reproduce

1. Make sure you have no `bitrex/xod-menu-system` installed
2. Hit File → Add Library `bitrex/xod-menu-system`
3. Wait for completion and expand the library in Project Browser

### Expected behavior

- I see no `menu-base` and `text-lcd-16x2-keypad-impl` because they are utilities

### Actual behavior

- I see all the patches including mentioned
- If I reload IDE, they hide and all start work as expected

**Comment by nkrkv** [comment]
Thank you for the report. I can confirm the bug

**Comment by evgenykochetkov** [comment]
At first glance this looks related to https://github.com/xodio/xod/issues/1547 🤔
