### ISSUE TITLE
0bh converts to 00000000b instead of 0Bh

### ISSUE THREAD

**Issue by Cesar-S** [xodio/xod#1699]
If a value of 0bh is loaded in pin, it is converted to binary.

### Environment

* Scope: desktop IDE
* Version: 0.27.0
* OS: Windows 10

### Steps to reproduce

1.  Create a byte output pin
2.  Load values with mini letter (a-b-c-d)

### Expected behavior

The letters change to capitals and assign the hex value

### Actual behavior

All change to capital, except b, value 0bh is convert  to 00000000b

![dependablepaltryhorseshoecrab-size_restricted 1](https://user-images.githubusercontent.com/4626896/53391291-afcdcb00-3974-11e9-9160-8357a130d26b.gif)

* PS: the error occurs when modifying 00h, if bh (0Bh) or bbh (BBh) is loaded there is no error.

**Comment by nkrkv** [comment]
Thanks for the report!

I’m almost sure it’s because the `b` character is also used to denote the binary base. The `0bh` literal is wrongly interpreted as binary and not hexadecimal as it should be.
