### ISSUE TITLE
Breadcrumbs hide tabs

### ISSUE THREAD

**Issue by Cesar-S** [xodio/xod#1718]
### Environment

* Scope: desktop IDE
* Version: 0.28.0
* OS: Windows 10

### Steps to reproduce

1.  Open various tabs 
2.  Open `wayland/ssd1306-oled-i2c/draw-xod-logo`
3.  Open `not-implemented-in-xod`

### Actual behavior

The other tabs are hidden, they are only visible after clicking on the node tab.

It happens when part of the code is very extensive. (I've seen it before, I do not remember with which nodes)

* PS: same behavior in `utility` node `ds1302-get` (in `cesars/ds1302/get-ds1302` node)

![CommonMeekBighornedsheep-size_restricted 1](https://user-images.githubusercontent.com/4626896/54172648-94c38680-445d-11e9-86fd-4ce8cd1a8282.gif)

**Comment by evgenykochetkov** [comment]
Fixed in #1719, released in 0.28.1
