### ISSUE TITLE
Difficulty in selecting and moving buses

### ISSUE THREAD

**Issue by Cesar-S** [xodio/xod#1721]
The area to select a `bus` is very small, and most of the time I end up selecting the `pin`. 🤦‍♂️  

Could a greater hidden area be made that occupies at least 50% of the cell? or invert the triangle but maybe it is not right.

![image](https://user-images.githubusercontent.com/4626896/54407432-98087d80-46bc-11e9-83da-388406a5131a.png)

**Comment by nkrkv** [comment]
It might be not obvious, but you can also drag by the label.

I agree however, a bus should detect hover whenever the cursor is put anywhere above the slot occupied by it.

Here’s a GIF demonstrating the current state.

![bus-select](https://user-images.githubusercontent.com/146383/54425178-be163800-4725-11e9-801b-a8dc52a468bd.gif)

**Comment by Cesar-S** [comment]
My problem arises here, I'm going to try to get used to selecting on the label.

![ObeseShadyAnaconda-small 1](https://user-images.githubusercontent.com/4626896/54433478-af6e5780-470a-11e9-9709-0a4dede06f38.gif)

**Comment by nkrkv** [comment]
The pins’ hotspot is bigger than the visual circle by-design. Otherwise, it would be too hard to point the pins while linking. We should polish bus node image somehow so that a xoder would not be tempted to drag it by pin.

**Comment by Cesar-S** [comment]
If I select the bus or node, the pins are active to connect, the connection could be deactivated when the node is selected.
