### ISSUE TITLE
Double click in project browser - nodo vs example

### ISSUE THREAD

**Issue by Cesar-S** [xodio/xod#1728]
The double click on the project navigator is ideal for examples, but in the case of a node I do not loveo convenient.

Example:
A library contains the application example, double click "the patch is ready to use"
If this example is dragged to another patch, only one frame is seen. (confusion for new user)

A node (composed of multiple nodes, or utility node) with a double click is open. (A new user can modify without realizing it and it will no longer work.

My question is, can we include something that differentiates node vs example, something like abstract, utility, deprecated,"patch"? and according to that allow not double click or block drag an example?

😕

PS: Unlike UT identification for example, this could be visible?

**Comment by nkrkv** [comment]
Hello! I agree that the semantic difference between examples and regular patches causes confusion and should be addressed somehow. However, GitHub issues is a task tracker. That is, what’s put here should be crystallized and have a notion of “done”.

To discuss how a problem might be solved, please, use https://forum.xod.io

Possibly related to (stale a bit) #653
