### ISSUE TITLE
Make `if-else` generic

### ISSUE THREAD

**Issue by nkrkv** [xodio/xod#1764]
Mentioned on [forum](https://forum.xod.io/t/if-else-boolean/2152). There’s no reason `xod/core/if-else` should limit `T`/`F`/`R` types to a particular set. The node should be truly generic.

### Acceptance criteria

- [ ] `xod/core/if-else` is no longer abstract and works with any type (in particular, numbers and booleans)
- [ ] `xod/core/if-else(xxx)` are deprecated in favor of the unified `if-else`

### How to test

- A tabtest in `workspace/test/test-core`

**Comment by Cesar-S** [comment]
Hi @nkrkv,  I know it's a closed topic, and sorry for consulting here, but is there any reason why `defer` is not truly generic?
