### ISSUE TITLE
Implement pulse-on-true-and-change

### ISSUE THREAD

**Issue by nkrkv** [xodio/xod#1789]
To follow [Quickstart hardware node control pin guidelines](https://github.com/xodio/xod/wiki/Hardware-Library-Guidelines#quickstart-nodes-control-pins) it is required to have a helper node in the pocket.

### xod/core/pulse-on-true-and-change

Emits a pulse when `IN` changes but only if `ACT` is true. Also emits a pulse when `ACT` becomes true. Useful to convert some item “enableness” to a series of update pulses right at the moments when these updates should be reflected.

| Dir | Pin  | Type    | Default | Description
| --- | ---- | ------- | ------- | -----------
| in  | ACT  | Boolean | True    |
| in  | IN | t1    |       |
| out | OUT | Pulse |   |

This order of `ACT` and `IN` allows to make the node variadic after #1144 

### Acceptance criteria

- [ ] The node works as described with at least numbers, strings, booleans, bytes, and colors

**Comment by brusherru** [comment]
Done in PR #1835. The new node called `act`.
