### ISSUE TITLE
Debug Code with Visual Studio Code

### ISSUE THREAD

**Issue by masterhung0112** [xodio/xod#1817]
Editor:
   Visual Studio Code

I am very sorry for a basic question.
But anyone can guide me how to put the breakpoint inside visual studio code (or any text editor, IDE) and debug the code for the entire project.

My steps are as following:

1. Start Chromium with debugging port 9222
/Users/xxx/Applications/Chromium.app/Contents/MacOS/Chromium --remote-debugging-port=922

2. Build the entire project at xod root folder
yarn build:browser

3. Start the webpack-dev-server for browser
yarn dev:browser

4. Create launch.json at xod root folder. VS Code will use this to attach to the Chrome and launch debugger
{
            "type": "chrome",
            "request": "attach",
            "name": "Attach Chrome against localhost",
            "port": 9222,
            "webRoot": "${workspaceFolder}/packages/xod-client-browser/dist",
            "sourceMaps": true,
            "address": "127.0.0.1",
}

5. in VS Code, I put a breakpoint in a source code like 
packages/xod-client/src/core/containers/App.jsx

6. In the Chrome browser, I start localhost:8080

But the VS Code never pause at any breakpoint that is not in xod-client-browser.

May anyone help share your development environment that may set the breakpoint and debug the XOD IDE code?
Many thanks.

**Comment by evgenykochetkov** [comment]
Hello!

Sorry, but I don't think any of the team ever used the workflow you described 🤔
Personally, I mostly use breakpoints while working on a single package.
