### ISSUE TITLE
Error publishing library update

### ISSUE THREAD

**Issue by Cesar-S** [xodio/xod#1826]
### Environment

* Scope: desktop IDE
* Version: 0.30.0 
* OS: Windows 10

When trying to upload the library update, the following error appears.

![image](https://user-images.githubusercontent.com/4626896/61495342-294f6f80-a98f-11e9-83dc-958fe7beac83.png)

**Comment by nkrkv** [comment]
Confirm. Thank you for reporting. Will release a hotfix very soon.

**Comment by evgenykochetkov** [comment]
Fixed in #1827
