### ISSUE TITLE
Change error clear conditions

### ISSUE THREAD

**Issue by nkrkv** [xodio/xod#1834]
### Rationale

Currently, we have error reset behavior which is impractical in real tasks. Two issues exist:

1. Errors on scalar values are cleared automatically before node evaluation when it is given a chance to recover. This contradicts to the documentation and intent.
2. Errors on pulse links get cleared at the end of the transaction. This introduces counter-intuitive effects when the sub-graph is recovered almost immediately after an error and works “fine” even if we can’t trust the data because there was the error

Let’s get rid of both issues.

### Acceptance criteria

- [x] Value-type outputs keep errors until a node’s `evaluate` emits a new non-error value explicitly
- [x] Pulse-type outputs _do_ lose errors right before recovering
- [x] Pulse-type outputs _do not_ lose errors at the end of a transaction
- [x] Docs are updated to describe the updated pulse errors behavior

**Comment by evgenykochetkov** [comment]
This was closed in #1858 and xodio/xod-docs#143
