### ISSUE TITLE
Latest versions missing on npm

### ISSUE THREAD

**Issue by w3cj** [xodio/xod#1843]
I'd like to use `xod/packages` in a project, but the latest version of most packages on npm is `0.21.0`.

* https://www.npmjs.com/package/xod-cli
* https://www.npmjs.com/package/xod-fs
* https://www.npmjs.com/package/xod-client
* https://www.npmjs.com/package/xod-arduino-deploy
* https://www.npmjs.com/package/xod-func-tools
* etc.

Will the latest versions be published? Or is there a technical limitation?

**Comment by nkrkv** [comment]
There are no technical limitations. Will publish soon and make the updates a part of the [release procedure](https://github.com/xodio/xod/wiki/Releasing-a-New-Version).

**Comment by evgenykochetkov** [comment]
Published!
