### ISSUE TITLE
Defer node simulation problem

### ISSUE THREAD

**Issue by Cesar-S** [xodio/xod#1874]
There is an error simulating defer node, forum topic here 
https://forum.xod.io/t/compiler-error-on-207-busses-in-versio-0-31-0/2663

if two defer are placed, the simulation works

![image](https://user-images.githubusercontent.com/4626896/66246000-ba5cf980-e6e7-11e9-969a-0b29c2396e3c.png)

**Comment by evgenykochetkov** [comment]
Hi!

I already fixed this in #1871, will release soon with a couple of other fixes.
