### ISSUE TITLE
XOD IDE can't find the specialization for `dht2x-device`

### ISSUE THREAD

**Issue by brusherru** [xodio/xod#1876]
Reported on forum: https://forum.xod.io/t/new-version-xod-dht2x-issues/2669

### Environment
* Version: 0.31.1

### Steps to reproduce
1. Place `dht2x-device` and `xod-dev/dht/read` node
2. Link them
3. Try to upload or simulate the patch

### Expected behavior
Everything is fine.

### Actual behavior
XOD IDE stops compilation with an error:
```
Specialization patch not found
Cannot find specialization read(dht2x-device) for abstract xod-dev/dht/read.
Try creating the missing patch in your project or install a library that provides such one.
```

### How to fix
Fix the input of `DEV` pin in the `xod-dev/dht/read(dht2x-device)`.

**Comment by evgenykochetkov** [comment]
The algorithm is fine.
The specialisation `xod-dev/dht/read(dht2x-device)` uses input for `dht11-device`.
