### ISSUE TITLE
Pulse signals generated from boolean rising edge through bus work incorrectrly

### ISSUE THREAD

**Issue by gabbapeople** [xodio/xod#1929]
The example of a counter which should start on `boot` and stop at `5`.

![1](https://user-images.githubusercontent.com/35202630/71079182-cfe8a800-219b-11ea-98cf-b773cb0b3fe6.png)

[patch.zip](https://github.com/xodio/xod/files/3977929/patch.zip)

### Steps to reproduce

Flash or simulate the attached patch.

### Expected behavior

The `select` should output `1` on `boot` and the counter should start.

### Actual behavior

The `select` and counter are hanging. The `select` output is `0`.

**Comment by evgenykochetkov** [comment]
During transpilation, the example patch gets flattened into this:
![Screen Shot 2020-02-05 at 20 42 00](https://user-images.githubusercontent.com/2527093/73868429-7cb8da80-4859-11ea-8009-72141ab79445.png)

Notice that the cast nodes between the `defer(boolean)` node and pulse inputs are missing.
If we run this flattened patch, the missing cast nodes are added and all works as expected:
![Screen Shot 2020-02-05 at 20 45 01](https://user-images.githubusercontent.com/2527093/73869400-3d8b8900-485b-11ea-9d98-573a8ce322fa.png)
