### ISSUE TITLE
Pulse-on-change type byte

### ISSUE THREAD

**Issue by Cesar-S** [xodio/xod#1938]
Please add `pulse-on-change` type byte.

I have it created in a personal library, but since it is now generic it would be better to be native in XOD

thanks

**Comment by nkrkv** [comment]
Good idea!

Do you feel the power to make a pull request to the `xod/core`?

**Comment by Cesar-S** [comment]
> Do you feel the power to make a pull request to the xod/core?

I have desktop Github, I could try it although I don't know much about working with github.

**Comment by nkrkv** [comment]
OK, feel free to try to make a PR. If you have problems we’ll implement the issue ourselves.
