### ISSUE TITLE
Problem with pulse-on-change(byte) and accumulate-string

### ISSUE THREAD

**Issue by Cesar-S** [xodio/xod#1973]
### Environment

* Scope: desktop IDE
* Version: 0.33.0

### Steps to reproduce

Try to narrow down your scenario to a minimal working/failing example. That is, if you have a big program causing a problem, start with deleting parts not relevant to the issue and observing the result: is the problem still there? Repeat until you get the most straightforward sequence of steps to reproduce the problem without any noise surrounding it.

[topic in forum](https://forum.xod.io/t/letter-or-number-adder/3353/12)

### Expected behavior

A patch with changes of byte-type values, which includes, if-else-v, accumulate-string and pulse-on-change (byte).
A flip-flop to verify the pulses.

At the change of value send a pulse and accumulate string

### Actual behavior

At the change of value it sends a pulse and but accumulate-string is blocked.

![336db5a2acff15a1fc3a40c62632df24036eafdc 1](https://user-images.githubusercontent.com/4626896/74839508-24c3ae80-5304-11ea-8ce2-9f1a90cac814.gif)

**Comment by nkrkv** [comment]
From what I see, the behavior is correct: you get a string with the following __six__ characters in it:

- `A` (41h)
- `\x00` (00h)
- `B` (42h)
- `\x00` (00h)
- `C` (43h)
- `\x00` (00h)

The NULL-termination character means “that’s all, guys, thank you” in C++. So if you want to get `ABC` you should filter-out nulls.

**Comment by Cesar-S** [comment]
Purchased and works correctly, thank .
