### ISSUE TITLE
Rotate de enviroment to work like fpga or PLCs

### ISSUE THREAD

**Issue by HeronDA** [xodio/xod#1989]
Hello, it would be possible to rotate the IDE to work from left to right and from top to bottom. I think it would be more functional and more like other similar environments, and even other technologies like FPGAs or PLCs.

Thanks!

**Comment by nkrkv** [comment]
Hello! Left-to-right vs top-to-bottom is a controversial topic with no right answer. XOD had to choose one camp. We have chosen top-to-bottom and this can’t be changed at the current point of time.
