### ISSUE TITLE
Update bug in https://xod.io/libs (C++)

### ISSUE THREAD

**Issue by Cesar-S** [xodio/xod#2044]
There is a bug in the C ++ update in web https://xod.io/libs , it still shows a code but the node now includes other nodes, and the main C ++ code is no longer that shown.

example: 
https://xod.io/libs/cesars/rich-uno-r3/rich-touch/

**Comment by nkrkv** [comment]
Hello! Thanks for the report. Here’s what I see on the page pointed as the example:

![image](https://user-images.githubusercontent.com/146383/93749846-49b63200-fc03-11ea-8c64-f0566323d6dd.png)

What’s wrong with it? What C++ code do you expect to see?

**Comment by Cesar-S** [comment]
Hi, the node is composed of multiple nodes.

![image](https://user-images.githubusercontent.com/4626896/93760291-1616e000-fbe2-11ea-89a2-0b010e2806b9.png)

![image](https://user-images.githubusercontent.com/4626896/93760417-5a09e500-fbe2-11ea-992f-13450a8f9fe3.png)


Although there is a code, that code is no longer the one shown on the page.

![image](https://user-images.githubusercontent.com/4626896/93760474-74dc5980-fbe2-11ea-9a2c-d8d5b17445c4.png)

**Comment by nkrkv** [comment]
Ah, I see. So, some obsolete implementation sticks when a node becomes composite.

Marking the issue as a bug.

**Comment by brusherru** [comment]
It's a bug on the website, that shows a stale C++ implementation... The code transpiles correctly.
So it's not a core 🤔 
Probably, we have to remove the C++ file at all, but I remember we got some arguments to leave it as is.
