### ISSUE TITLE
When i press 'h' in login - all clean

### ISSUE THREAD

**Issue by artech53** [xodio/xod#2100]
### Environment

* Scope: desktop IDE,
* Version: 0.37.2 | dev 
* OS: Windows 10 
* Machine: AMD Ryzen 5 3400G, 16 GB RAM

### Steps to reproduce
Open login panel
Try input login name with 'h' symbols
When you press 'h' all login clean

**Comment by nkrkv** [comment]
Thanks for the report! Clearly a bug.

IDE considers the `h` press as a hotkey, even if an input is focused. Dumb workaround: type your credentials elsewhere and just paste via clipboard.

**Comment by artech53** [comment]
Yes, I did.:)

**Comment by evgenykochetkov** [comment]
The issue was fixed in #2101 and released in `v0.37.3` (#2102)
