### ISSUE TITLE
Cannot log-in (Cloud compilation limits exceeded)

### ISSUE THREAD

**Issue by imjarek** [xodio/xod#2111]
### Environment

* Scope: desktop IDE
* Version: 0.38.0
* OS: Ubuntu 20.04.2 LTS
* Machine: i3, 8 GB RAM

### Steps to reproduce

Because of "Cloud compilation limits exceeded" error for guest user, i attempted to login for a few times, but no avail.
Login button gets inactive after pressing down and nothing happens. Because of this I can give it another try only application restart. I can successfully login to xod.io with these credentials.

### Expected behavior

UI should indicate I'm logged-in or at least show an error (login or password invalid)

### Actual behavior

Nothing happens

![image](https://user-images.githubusercontent.com/10037816/125143776-6a189400-e124-11eb-8dc9-4dc1c2d69901.png)

**Comment by Suanloke** [comment]
Can't log in.  I think there are some authentication issue at back end.  After logging in, as indicated above, nothing happens.
In my case, Windows 10.

**Comment by knopki** [comment]
Confirmed. Some sort of backend problem.

**Comment by knopki** [comment]
Should work now. Feel free to reopen the issue if not.
