### ISSUE TITLE
Popups should close each other

### ISSUE THREAD

**Issue by brusherru** [xodio/xod#477]
### Steps to reproduce
- Open xod-client-electron
- Click in the menu "Create new project"
- Click in the menu "Open project"

### Expected behavior
The project has been opened and I can begin work with it.

### Actual behavior
The project was opened, but I see "Create new project" popup over it. So I have to close it first.

**Comment by nkrkv** [comment]
Looks outdated. I’ve tried to run a few sequences of popup dialogs canceling each other and they work as one would expect. The only minor overlap found is between a popup dialog and suggester box which can co-exist. Should they cancel each other or not is a separate question which does not affect IDE significantly.

So, I tend to consider this issue stale.
