### ISSUE TITLE
Long label in Nodes

### ISSUE THREAD

**Issue by brusherru** [xodio/xod#489]
### Steps to reproduce
- Open any patch
- Place any node
- Set a long label for this node

### Expected behaviour
There are two ways, we have to decide which is better:
A. Node became bigger like it has more pins. The label could be wrapped to the next line if it's very long.
B. Just place the ellipses at the end of visible part of the label inside Node (and align text to the left).

### Actual behaviour
The label is going out of Node bounds.

---
I think that expected behaviour A is better for product and it will allow us to create cool comment nodes that can be read directly on the patch. But it's harder to implement and maybe right now we should just implement behaviour B. And if someone wants to write comments — let them write comments in the description field.

**Comment by nkrkv** [comment]
It was fixed inside #742
