### ISSUE TITLE
Handle error reporting

### ISSUE THREAD

**Issue by alexander-matsievsky** [xodio/xod#666]
### Rationale

In some cases `xodc` spits out error object serialization. This should be transformed to human-friendly descriptive messages.

### Acceptance criteria

- [ ] https://github.com/xodio/xod/pull/665#discussion_r127158094
- [ ] https://github.com/xodio/xod/pull/665#discussion_r127157235
- [ ] https://github.com/xodio/xod/pull/665#discussion_r127158687

**Comment by nkrkv** [comment]
Superceeded by #884
