### ISSUE TITLE
Typing `h` in an input toggles Helpbar

### ISSUE THREAD

**Issue by nkrkv** [xodio/xod#759]
### Steps to reproduce

1. Open any patch
2. In the description field type “hula hoop”

### Expected behavior

Just “hula hoop” gets entered, the Helpbar does not appear.

### Actual behavior

- The help bar toggles on every `h` press.
- The same occurs if I edit a comment
- The same occurs if I bind a value

**Comment by evgenykochetkov** [comment]
🤔 
This [should not be happening](https://github.com/xodio/xod/blob/master/packages/xod-client/src/editor/containers/Editor.jsx#L59)
Can't reproduce on stage version either.
Is this in desktop or web IDE?

**Comment by nkrkv** [comment]
Desktop IDE. Linux. And yes, I have this line. Any thoughts how can I assist?
