### ISSUE TITLE
repeated typo in core node descriptions: "Ouputs" instead of "Outputs"

### ISSUE THREAD

**Issue by awgrover** [xodio/xod#788]
### Steps to reproduce

- visible when you look at the description for several nodes
- do the "search" thing and type "ouput"

### Expected behavior

Spell it "Outputs"

### Actual behavior

Says things like "Ouputs false if and only if both inputs are true"

### Console output

none

### How to fix
`rgrep -i ouput .` seems to look safe for:

```
find . -type f | xargs sed -i 's/ouput/output'
find . -type f | xargs sed -i 's/Ouput/Output'
```

**Comment by nkrkv** [comment]
Nice catch! Thanks
