### ISSUE TITLE
Clear project browser UI

### ISSUE THREAD

**Issue by nkrkv** [xodio/xod#928]
### Mockup

![preview](https://user-images.githubusercontent.com/146383/33563290-95dcf85e-d928-11e7-925d-2eb0716754ee.png)

### Icons

- [project.zip](https://github.com/xodio/xod/files/1527894/project.zip)
- [libs.zip](https://github.com/xodio/xod/files/1527897/libs.zip)
- [context-tools-list.zip](https://github.com/xodio/xod/files/1538320/context-tools-list.zip)
- [add-lib.zip](https://github.com/xodio/xod/files/1538322/add-lib.zip)
- [new.zip](https://github.com/xodio/xod/files/1538520/new.zip)

### Acceptance criteria

- The colorful icons are used
- The current node filter/tab is removed
- Splitters are drawn as in the mockup
- Patch actions are hidden in the context menu

**Comment by brusherru** [comment]
@nkrkv I need icons for "context menu" and "add library".

**Comment by nkrkv** [comment]
Sure. Added them to the “Icons” section
