### ISSUE TITLE
Tooltipish node help in project browser

### ISSUE THREAD

**Issue by nkrkv** [xodio/xod#930]
### Mockup

![01](https://user-images.githubusercontent.com/146383/33565363-f774ca74-d92d-11e7-8ef9-b8bd4409ef59.png)
![02](https://user-images.githubusercontent.com/146383/33565365-f9364284-d92d-11e7-9f11-d38238b73b10.png)
![03](https://user-images.githubusercontent.com/146383/33565368-fab28d3e-d92d-11e7-956b-3b8280ba592c.png)
![04](https://user-images.githubusercontent.com/146383/33565370-fbc72284-d92d-11e7-9556-3e17692ecb05.png)
![05](https://user-images.githubusercontent.com/146383/33565373-fd01e882-d92d-11e7-920c-8f5694819caf.png)

### Acceptance criteria

- [x] The help is invoked via node context menu
- [x] The tooltip switches to the new node when it is selected
- [x] The tooltip closes on (x) click or ESC
- [x] Width grows with node width grow
- [x] Nodes with 8+ pins in width are scaled down on preview
- [x] The tooltip never goes out of the screen. If too low, the tip moves down, the content rectangle stays visible

**Comment by brusherru** [comment]
There are few unresolved issues in the design:
- What will be with help box and pointer when we scroll Project Browser pane? (item still visible, but goes upward)
- The same thing, but when the item goes out of the visible area of Project Browser?
- When it opened and User clicks on another item — should it "jump" to this item or just move the pointer (if possible to do it without "jumping")?

The similar story with the issue about quick search.
