### ISSUE TITLE
Drag and drop of Nodes breaks Patch working area in IDE

### ISSUE THREAD

**Issue by brusherru** [xodio/xod#944]
### Steps to reproduce
1. Open `welcome-to-xod` project
2. Open `01-hello` patch
3. Open `welcome-to-xod` in Project Browser
4. There are two cases:
4.1. Try to drag&drop Patch to itself as a Node (`01-hello` into opened `01-hello`)
4.2. Try to drag&drop Patch somewhere missing Patch area or Project Browser (E.G. tabs / menu / helpbar and etc)
5. After any of this actions — try to select Node / Comment / drag&drop something on the Patch and etc. (Actions in the Project Browser, Inspector, Menu and etc — still works)

+ If you try to drag&drop another Node (E.G. `02-deploy`) — it will fix Patch working area.

### Expected behavior
In the first case, IDE should show an Error message that PatchNode could not be placed in itself.
In the second case, nothing happens, IDE still works.

### Actual behavior
It silently breaks any interactions with Patch area.

### Console output
It's empty.

### How to fix
It seems that the error in the managing of Drag&Drop and state. Like in bad cases it doesn't remove a "monitor" that catches object to place on the Patch.

**Comment by evgenykochetkov** [comment]
Yep, need to specify [endDrag](https://react-dnd.github.io/react-dnd/docs-drag-source.html) for `DragSource`
https://github.com/xodio/xod/blob/4dc6d45fd05aee994c11acd5abcb0c6dc6da052e/packages/xod-client/src/projectBrowser/components/PatchGroupItem.jsx#L12-L17

not just `drop` for `DropTarget`
