### ISSUE TITLE
Entering invalid lib name in library suggester results in repeated network requests

### ISSUE THREAD

**Issue by evgenykochetkov** [xodio/xod#970]
### Steps to reproduce

1. Open IDE
2. Select "file -> add library" from the main menu
3. Type something like `xod/common-`
4. Observe console and network tab

### Expected behavior

There is a single check for a library with this name

### Actual behavior

IDE repeatedly tries to get info about `xod/common-`

### How to fix

https://github.com/xodio/xod/blob/ab7bac3985b52f1f09c593899d0e5f3ab69f0b46/packages/xod-pm/src/fetch.js#L36-L63

- check for more cases, not only 404(or validate lib name before checking)
- do not use "original" `fetchLibData` function as a retry function, because it will never stop

**Comment by nkrkv** [comment]
Note, any 4xx error means that the *client* (i.e. XOD IDE) is wrong with its request arguments. Replaying a 4xx request will fail again. So `retryExcept404` should really be `retryExcept4xx`.
