### ISSUE TITLE
Double click on patch board does not work on Windows browser IDE

### ISSUE THREAD

**Issue by nkrkv** [xodio/xod#985]
### Steps to reproduce

1. Open *browser* IDE on Windows
2. Double-click a node, the patch board, a comment

### Expected behavior

Node drill-down, quick search, edit comment

### Actual behavior

Nothing

### Console output

Nothing

### Details

- Does *not* appear in Linux, both IDE flavors
- Does *not* appear on Windows, desktop IDE
- Double-click on project browser items work on every system

**Comment by brusherru** [comment]
Could not reproduce bug anymore on the same PC where it was detected.
